### PR TITLE
Magnetic

### PR DESCRIPTION
**Pull request by Fohlen**
Update to the new website layout including the following features:
- Blog page (sorted by year or single post)
- Team page (retrieves all public members from Github api)
- Content page (lists entries in our forum / "official" content)
- A RSS feed, to provide news externally.

The following features are still missing/will be done later
- ajax-based search through file meta (needs an optimised posts algorithm, maybe a json-backend)
- A json-based mapping of uid=player name on the team page (suggested by @Croydon)
- We need more social buttons. This is done in `assets/img/stretch_hover.png`.

Following are screenshots of what it looks like:
screenshot_team
screenshot_content
screenshot_blog
screenshot_post

### CODE REVIEW

**Comment by Croydon** [comment]
Is it still having a landing page with a big screenshot or video?

**Comment by Fohlen** [comment]
Could be added using youtube-api.

**Comment by a-teammate** [comment]
already looks pretty cool,
maybe we should remove the images in the team-section (i mean github is not instagram and i dont want to be judged by my looks when i do programming work) and present some more general info there instead (or replace the "the team" section with a section "the idea" or sth and make it a subtopic?).
Another thing which would be nice if the blog page landing page could already show some lines of the content, to get the readers attention (headline only is not enough for a lot of people to click on "show more"). othewise great :)

**Comment by Fohlen** [comment]
In that case we need a mapping of github-id with infos.
Anyhow I like the pictured preview.. it gives an idea of what different people are contributing to the project.
As for the content page:
You do see the full articles (including images etc) and a "Read more" button.
As for the landing page:
I will try to include as many pictures/videos as possible without screwing up the layout .. if you have any suggestions let me know.

**Pull request merged**
